# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test

on:
  push:
    branches:
      - "**"
    paths:
      - src/**
      - package.json
      - tsconfig.*
jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: current

      - uses: pnpm/action-setup@v2
        with:
          run_install: false
          version: 7.5.2
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install --frozen-lockfile --prefer-offline --silent --reporter silent
      - run: pnpm ci:test

      - name: Create a new tag
        run: pnpm ci:tag
        env:
          GITHUBTOKEN: ${{ secrets.GIT_TOKEN }}
          LASTCOMMITSHA: ${{ github.SHA }}
